### ISSUE TITLE
Progressively edit

### ISSUE THREAD

**Issue by Kitenite** [XD2Sketch/gpt-react-designer#5]
Hello,
Would love to feed the code back into the LLM for continual editing and show chat history.

ACs:
- When a user edits the code in the editor manually the displayed component gets update automatically
- Instead of sending one prompt we should change the behavior to have a chat history
- A user can send multiple prompts and adjust the appearance of the component based on prompts
- We need to introduce a button to start a new chat to generate a new component
- Add a side bar with a chat history similar to ChatGPT

**Comment by kgoedecke** [comment]
@niels-bosman do you think this is something thats fairly easily achievable?

**Comment by kgoedecke** [comment]
@niels-bosman @Kitenite I've edited the initial issue description and added ACs to describe what we should do as part of this ticket. Do you see anything missing from the list?

**Comment by Kitenite** [comment]
That looks pretty good!
I implemented a version of that in a Svelte clone here: https://github.com/Kitenite/llm-web-designer/blob/main/client/src/components/Chat.svelte

It doesn't have chat history but that's easy to add. I'm just checking if code already exist to change the prompt.

Not super comfortable contributing here until there's a clear license

**Comment by kgoedecke** [comment]
@Kitenite thanks for the reminder, I've approved your latest PR, so we can go ahead. I've also just had a look at your repo this looks very promising.

**Comment by Kitenite** [comment]
Awesome thanks for doing that @kgoedecke. One more thing I noticed from my implementation is that it takes progressively longer to edit larger components due to token count. Ideally, we would be sending only the relevant part of the component to the LLM (with some preprocessing)? 

What are your thoughts?

**Comment by kgoedecke** [comment]
@Kitenite so good news here, @niels-bosman worked on this and the PR is open. Would be great if you could give it a try: https://github.com/XD2Sketch/gpt-react-designer/pull/8

**Comment by niels-bosman** [comment]
I'll mark this as closed since we can now do this.
